
name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # target linux (remote hosts) and macos (local dev)
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.4
        env:
          # only 64 bit architectures, install freetds before build
          CIBW_ARCHS_LINUX: x86_64
          CIBW_BEFORE_ALL_LINUX: apt-get install freetds-dev || yum install -y freetds-devel || apk add --upgrade freetds-dev
          CIBW_BEFORE_ALL_MACOS: brew install freetds
          CIBW_ARCHS_MACOS: x86_64 arm64

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
