name: Publish
on:
  push:
    branches:
      - master
      - tox # TODO: delete when done testing
    tags:
      - v*


jobs:
  publish-sdist:
    name: Build and publish ctds to pypi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Build ctds sdist
        run: |
          python setup.py sdist

      - name: Publish ctds sdist to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish ctds sdist to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TODO }} # ${{ secrets.PYPI_API_TOKEN }}

  publish-docs:
    name: Build and publish ctds docs to Github Pages
    needs: publish-sdist
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Build ctds docs
        run: |
          tox doc
