name: CI/CD
on: [push, pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - macos-11.0
        freetds-version:
          - 0.91.112
          - 0.92.405
          - 0.95.95
          - 1.00.80
          - 1.1.24
          - 1.2.10
        python-version:
          - 3.9
          - 3.8
          - 3.7
          - 3.6
          - 2.7

    steps:
      - uses: actions/checkout@v2

      - name: 'Cache FreeTDS ${{ matrix.freetds-version }}'
        id: cache-freetds
        uses: actions/cache@v2
        with:
          path: |
            build/freetds-${{ matrix.freetds-version }}/include
            build/freetds-${{ matrix.freetds-version }}/lib
          key: ${{ matrix.os }}-freetds-${{ matrix.freetds-version }}

      - name: 'Compile FreeTDS ${{ matrix.freetds-version }}'
        if: steps.cache-freetds.outputs.cache-hit != 'true'
        run: make freetds-${{ matrix.freetds-version }}

      - name: 'Setup Python'
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip tox tox-gh-actions

          echo "CTDS_INCLUDE_DIRS=$GITHUB_WORKSPACE/build/freetds-${{ matrix.freetds-version }}/include" >> $GITHUB_ENV
          echo "CTDS_LIBRARY_DIRS=$GITHUB_WORKSPACE/build/freetds-${{ matrix.freetds-version }}/lib" >> $GITHUB_ENV
          echo "CTDS_RUNTIME_LIBRARY_DIRS=$GITHUB_WORKSPACE/build/freetds-${{ matrix.freetds-version }}/lib" >> $GITHUB_ENV

      - name: 'Run tests (Python: ${{ matrix.python-version }}, FreeTDS: ${{ matrix.freetds-version }})'
        run: |
          tox

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          directory: ./build/coverage/
          fail_ci_if_error: true
          functionalities: 'gcov'
          verbose: true
