name: Automated tests and code checks
on: [push, pull_request]

jobs:
  freetds:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        freetds-version:
          #- 0.91.112
          #- 0.92.405
          #- 0.95.95
          #- 1.00.80
          - 1.1.24
          - 1.2.10
    steps:
      - uses: actions/checkout@v2

      # Compile FreeTDS and store it for use in later jobs.
      - name: 'Compile FreeTDS ${{ matrix.freetds-version }}'
        uses: 'actions/upload-artifact@v2'
        with:
          name: ${{ matrix.os }}-freetds-${{ matrix.freetds-version }}
          path: |
            build/freetds-${{ matrix.freetds-version }}/include/
            build/freetds-${{ matrix.freetds-version }}/lib/
          if-no-files-found: error

  tests:
    runs-on: ${{ matrix.os }}
    needs: freetds
    strategy:
      matrix:
        os: [ubuntu-latest]
        freetds-version:
          #- 0.91.112
          #- 0.92.405
          #- 0.95.95
          #- 1.00.80
          - 1.1.24
          - 1.2.10
        python-version:
          - 3.9

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip tox tox-gh-actions

      - uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.os }}-freetds-${{ matrix.freetds-version }}

      - name: 'Run tests (Python: ${{ matrix.python-version }}, FreeTDS: ${{ matrix.freetds-version }})'
        env:
          CTDS_INCLUDE_DIRS: build/freetds-${{ matrix.freetds-version }}/include
          CTDS_LIBRARY_DIRS: build/freetds-${{ matrix.freetds-version }}/lib
          CTDS_RUNTIME_LIBRARY_DIRS: build/freetds-${{ matrix.freetds-version }}/lib
        run: |
          tox
